services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnet
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.1
    ports:
      - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - esnet

  typeahead-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - COM_GRIDDYNAMICS_ES_GRADUATION_PROJECT_ESHOST=http://elasticsearch:9200
    networks:
      - esnet

volumes:
  esdata:

networks:
  esnet:
    driver: bridge